### PR TITLE
Add GTG caching, Fix timeouts, Fix uuid logging

### LINKED ISSUE #7: No timeout on healthcheck connection to Smartlogic
The healthcheck does not appear to have any timeout, so it can report success itself whilst causing dashing to alert, if the response from Smartlogic takes several seconds.

### LINKED ISSUE #9: Only log "Completed notification of concepts" if there are UUIDs in the list
https://github.com/Financial-Times/smartlogic-notifier/blob/master/notifier/service.go#L80

### PR DESCRIPTION
**Pull request by geoah**
### Changelog

* Only log when there are uuids; Closes #9
* Reduce end to end http client timeout to 5s; Closes #7
* Cache successful smartlogic gtg checks for 60s

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -110,7 +116,13 @@ func main() {
 
 		handler := notifier.NewNotifierHandler(service)
 		handler.RegisterEndpoints(router)
-		monitoringRouter := handler.RegisterAdminEndpoints(router, *appSystemCode, *appName, appDescription)
+		monitoringRouter := handler.RegisterAdminEndpoints(
+			router,
+			*appSystemCode,
+			*appName,
+			appDescription,
+			time.Second*time.Duration(*smartlogicHealthCacheDuration),
```
Comment (david-smith-ft) [inline main.go]: I'd use a string for the argument and then time.ParseDuration rather than magically turning it into seconds.  Gives us a bit more freedom.  We can still have it default to 60 seconds if the value is invalid.

**Comment by geoah** [comment]
[Add caching to smartlogic-notifier health check and good to go checks so it doesn't hammer smatlogic's api.](https://trello.com/c/CuYh8F6E/112-add-caching-to-smartlogic-notifier-health-check-and-good-to-go-checks-so-it-doesnt-hammer-smatlogics-api)

File: main.go [hunk 2]
```diff
@@ -91,6 +97,13 @@ func main() {
 	log.SetFormatter(&log.JSONFormatter{})
 	log.Infof("[Startup] %s is starting", *appSystemCode)
 
+	smartlogicHealthCacheDuration, err := time.ParseDuration(*smartlogicHealthCacheFor)
+	if err != nil {
+		log.Fatal("Invalid smartlogicHealthCacheFor duration")
```
Comment (david-smith-ft) [inline main.go]: If you can't parse the duration, I'd set a default like how log levels are dealt with.

File: main.go [hunk 3]
```diff
@@ -91,6 +97,13 @@ func main() {
...
+	}
+
+	log.Infof("Caching health for %s", smartlogicHealthCacheDuration)
```
Comment (david-smith-ft) [inline main.go]: This should probably be clear it's successful healthchecks that are cached, not all of them.

File: notifier/handlers.go [hunk 4]
```diff
@@ -120,8 +120,8 @@ func (h *Handler) RegisterEndpoints(router *mux.Router) {
 	router.Handle("/concept/{uuid}", getConceptHandler)
 }
 
-func (h *Handler) RegisterAdminEndpoints(router *mux.Router, appSystemCode string, appName string, description string) http.Handler {
-	healthService := NewHealthService(h.notifier, appSystemCode, appName, description)
+func (h *Handler) RegisterAdminEndpoints(router *mux.Router, appSystemCode string, appName string, description string, cacheSmartlogicSuccessFor time.Duration) http.Handler {
```
Comment (david-smith-ft) [inline notifier/handlers.go]: Same naming concerns around `cacheSmartlogicSuccessFor`

Comment (geoah) [reply notifier/handlers.go]: Renaming to `healthcheckSuccessCacheTime`

**Comment by geoah** [comment]
[Smartlogic notifier - Cache successful health check responses from API so we don't hammer the API](https://trello.com/c/X3OXdZce/73-smartlogic-notifier-cache-successful-health-check-responses-from-api-so-we-dont-hammer-the-api)
